{% set name = "textacy" %}
{% set version = "0.7.0" %}
{% set sha256sum = "7d8214deed4c8c787e9285b327e6466a2f469b8f0876c7cd59ca19cc2f189ac8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win32 or linux32]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - backports.csv >=1.0.1  # [py2k]
    - cachetools >=2.0.0
    - cld2-cffi >=0.1.4
    - cytoolz >=0.8.0
    - ftfy >=4.2,<5.0.0
    - ijson >=2.3
    - matplotlib >=1.5
    - networkx >=1.11
    - numpy >=1.9,<2.0.0
    - pyemd >=0.3.0
    - pyphen >=0.9.4
    - python-levenshtein >=0.12.0
    - requests >=2.10.0
    - scipy >=0.17.0
    - scikit-learn >=0.17.0
    - spacy >=2.0.0
    - tqdm >=4.11.1
    - unidecode >=0.04.19

test:
  commands:
    - python -m textacy -h
  imports:
    - textacy
    - textacy.cache
    - textacy.constants
    - textacy.corpus
    - textacy.datasets
    - textacy.doc
    - textacy.export
    - textacy.extract
    - textacy.io
    - textacy.keyterms
    - textacy.lexicon_methods
    - textacy.math_utils
    - textacy.network
    - textacy.preprocess
    - textacy.similarity
    - textacy.spacier
    - textacy.spacy_pipelines
    - textacy.spacy_utils
    - textacy.text_stats
    - textacy.text_utils
    - textacy.tm
    - textacy.viz
    - textacy.vsm

about:
  home: https://github.com/chartbeat-labs/textacy
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: higher-level NLP built on spaCy
  description: |
    textacy is a Python library for performing higher-level natural language
    processing (NLP) tasks, built on the high-performance spaCy library. With
    the basics --- tokenization, part-of-speech tagging, dependency parsing,
    etc. --- offloaded to another library, textacy focuses on tasks facilitated
    by the ready availability of tokenized, POS-tagged, and parsed text.
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://chartbeat-labs.github.io/textacy/
  dev_url: https://github.com/chartbeat-labs/textacy

extra:
  recipe-maintainers:
    - rmax
    - mageky
    - bdewilde
