# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic



matrix:
  include: []
script:
- export CI=travis
- export GIT_BRANCH="$TRAVIS_BRANCH"
- export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})
- if [[ "${TRAVIS_PULL_REQUEST:-}" == "false" ]]; then export IS_PR_BUILD="False";
  else export IS_PR_BUILD="True"; fi

- if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.scripts/run_osx_build.sh; fi
