travis:
  secure:
    BINSTAR_TOKEN: EB5yTwxvc9fOIkkioO+M2PXCKByGK5B6uWJyPCh51VN6MwA2l/apT2nAahYEsgh+Rw9pLBP6CWhtwiHzXB2z5B6mJhtKRbTibi7hTLrMGjgNCL7A/HSLSYZeYUuNvk55ppO3n6Bp1Iix9vStvuZOCSdhvvTQF9LuIDyT/2RmQF4KAliptEdRhOcCzyFg9oDVDYz8UrJZzyWKJ6WEWIkApiKmI2u5m44J/nzzjlfyCN7kVxrC566TknRSvuIoMLMplCnRMenLAl0IVJzYOAxB1wz/q/R5O5qJEpZqkmCaD/TxQZOp8Bly3MD8duhrRFX66EnVypaD5ufFpE1QNlTf+M7PUUziLfmLIlPqGLmonEaF3m3XBA9udiLn76ROn3uLmzq/Pk5suALc0DBM0TKL1Z15HCWNmm54YISSx51bKSh/NOml/IM6qW497H2k59maK5JdASog5sswIY3fltEVyUpqAgvZWwK9QyzRAwvXUPf2aRMOvBgCAEbLd5HU23At60UHmfSGzRPzbqr+OXA4Z9MPuQ8mWgrxhg/3tY105t1ZtF0bHu+VyHTLs2VOM5TVBuO7+3FTqfGGzLWPSwMePQS1wkxN8TW87Z9ExDZL/ZK4YMzkbK52Y16zHYCHxv/v2gJX2C6GD4Uo29VzGYQMfT05kDUnGFU4MYQ4xOSo83w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
