travis:
  secure:
    BINSTAR_TOKEN: tIu4M6/CZsk7atcTGYC//PSoFgVugSNoP/eiQR8xMiyLvgeqdQ5DSGgQQYXI2oE33k1J6GsZY0jiQbijpXSNf7ARbAL1daVLRDrIIMKdEoEVNKwbHRhG5rzswXQndP7Dy/HZIS8MWPzNfatuCp9FNNLND4EsgdluwXG3g3CLGsi7G1cyl66CrIa4SA/8iKlIhehMs/7K/jMnrmjc0FVHOdN1uz17lBxhnHCNi6gUQqAT2jfDXWOfQ4fSspPK5GzMYryVWZRu7Vg1aBz1J9o6E85iN4bQRju3osVWbU6IrBzP5tr0k8gGi9xxNwhd0dkICHoq5gCp7V9/G128y5gq/GCrSj7q/dZ2Ox2EC7MQ9Q5/VcaouYnRuc5f9C+FS1U6V2YY/StHfxeYkeA/umZySGNdNs4GVq648SV8K7GKh7URLjgpzA36YGgH+acoKeK8XIEyFP111Np3/IGXOVDIM/EZSyUkMYDSWtZKsFS+gkn7Femz1cfcTpYQVABpB6yRSiRuN6rwojPfRSWkS41TGxo6Vsufsut5Um9EZ0tS2mi8z4rqB+UWTEs5A473i8ln3Rx9LyTaXK7ZKIsjz65pPe76Zx3B30O1Kr90jXU4LtKGJ9GEE5mww5QmtBPuRZnFToInOwYR99NW+OtH/oiWO3vhI1/8GbOfG0pNcBdlPq0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
